require_relative '../rn68/node_modules/react-native/scripts/react_native_pods'
require_relative '../rn68/node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

target 'ios11-using-rn' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'rn68', path: '../rn68'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => '../rn68/node_modules/react-native',
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end
